function [ o ] = possible_offsets( a,b,n,corners )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
    if corners
        o = [...
            -1 0;...
            1 0;...
            0 -1;...
            0 1;...
            -1 -1;...
            1 -1;...
            -1 1;...
            1 1];
    else
        o = [...
            -1 0;...
            1 0;...
            0 -1;...
            0 1];
    end
    
    
    c=1;
    while c<=size(o,1)
        if ( o(c,1)==-1 && a==1 ) || ( o(c,1)==1 && a==n ) ||...
                ( o(c,2)==-1 && b==1 ) || ( o(c,2)==1 && b==n )
            o(c,:)=[];
        else
            c=c+1;
        end
    end
    
end

